import type { FallbackType } from '../data/types'

/** Maps entity IDs to their fallback illustration type */
export const characterFallbacks: Record<string, FallbackType> = {
  marika:           'golden-order',
  radagon:          'golden-order',
  godfrey:          'war',
  godwyn:           'golden-order',
  morgott:          'omen',
  mohg:             'blood',
  ranni:            'moon',
  rennala:          'moon',
  radahn:           'war',
  rykard:           'serpent',
  malenia:          'rot',
  miquella:         'haligtree',
  maliketh:         'death',
  melina:           'flame',
  fia:              'death',
  d:                'death',
  rogier:           'character',
  gideon:           'golden-order',
  goldmask:         'golden-order',
  corhyn:           'golden-order',
  'dung-eater':     'ending-despair',
  blaidd:           'beast',
  iji:              'war',
  seluvis:          'moon',
  millicent:        'rot',
  gowry:            'rot',
  godrick:          'golden-order',
  fortissax:        'dragon',
  placidusax:       'dragon',
  'gloam-eyed-queen': 'flame',
}

export const regionFallbacks: Record<string, FallbackType> = {
  limgrave:             'golden-order',
  stormveil:            'war',
  'peninsula-llorosa':  'character',
  liurnia:              'moon',
  'raya-lucaria':       'moon',
  caelid:               'rot',
  'altus-plateau':      'golden-order',
  leyndell:             'golden-order',
  'mt-gelmir':          'serpent',
  mountaintops:         'flame',
  'consecrated-snowfield': 'haligtree',
  haligtree:            'haligtree',
  mohgwyn:              'blood',
  'deeproot-depths':    'death',
  nokron:               'nox',
  nokstella:            'nox',
  'lake-of-rot':        'rot',
  'farum-azula':        'dragon',
}

export const factionFallbacks: Record<string, FallbackType> = {
  'orden-dorado':         'golden-order',
  'dos-dedos':            'golden-order',
  'tres-dedos':           'frenzied-flame',
  'cuchillos-negros':     'moon',
  'pieles-de-dios':       'flame',
  nox:                    'nox',
  'dragones-antiguos':    'dragon',
  'hombres-bestia':       'beast',
  omens:                  'omen',
  misbegotten:            'beast',
  albinauricos:           'haligtree',
  'cleanrot-knights':     'rot',
  redmanes:               'war',
  'volcano-manor':        'serpent',
  'bloody-fingers':       'blood',
  'those-who-live-in-death': 'death',
  deathbirds:             'death',
  'kindred-of-rot':       'rot',
  perfumers:              'golden-order',
  'raya-lucaria':         'moon',
  caria:                  'moon',
}

export const glossaryFallbacks: Record<string, FallbackType> = {
  'elden-ring':       'ending-fracture',
  'bestia-elden':     'cosmic',
  'voluntad-mayor':   'golden-order',
  'dioses-exteriores': 'cosmic',
  crucible:           'beast',
  erdtree:            'golden-order',
  'golden-order':     'golden-order',
  'destined-death':   'death',
  'rune-of-death':    'death',
  deathroot:          'death',
  'those-who-live-in-death': 'death',
  empyrean:           'golden-order',
  'shadow-bound-beast': 'beast',
  'great-rune':       'ending-fracture',
  grace:              'golden-order',
  tarnished:          'war',
  'scarlet-rot':      'rot',
  'unalloyed-gold':   'haligtree',
  'frenzied-flame':   'frenzied-flame',
  'formless-mother':  'blood',
  'dark-moon':        'moon',
  'black-flame':      'flame',
  ghostflame:         'death',
  bloodflame:         'blood',
  haligtree:          'haligtree',
  'age-of-stars':     'ending-stars',
}

export const endingFallbacks: Record<string, FallbackType> = {
  fracture:           'ending-fracture',
  order:              'ending-order',
  duskborn:           'ending-dusk',
  despair:            'ending-despair',
  'frenzied-flame':   'ending-frenzied',
  'age-of-stars':     'ending-stars',
}
